import localFont from "next/font/local";
import { Container, Typography } from '@mui/material';
import Header from './components/Header';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Product Import APP",
  description: "Generated by Ajay Ashok",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Container maxWidth="md" style={{ textAlign: 'center', marginTop: '2rem' }}>
          <Typography variant="h5" gutterBottom>
            Welcome to Product upload module!
          </Typography>
          {children}
        </Container>
      </body>
    </html>
  );
}
